### ISSUE TITLE
Place selected keywords in URL of /TASKS and /CROWDS so the selection can be bookmarked and shared

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#182]
For CROWDS and TASKS, it would be nice to have the selected tag in the URL. Like:

https://mobbr.com/#/crowds/brainstorm/media

(Does not work right now).

Summarising: every tag that is selected on the https://mobbr.com/#/crowds and https://mobbr.com/#/tasks pages should be added to that URL and when a user goes back to this URL, these tags should be selected again.

**Comment by davidsemakula** [comment]
@patricksavalle I want to have a go at this issue

From what I gather the final Uris should be this format
https://mobbr.com/#/crowds/:keywords
https://mobbr.com/#/tasks/:keywords

However example of expected behavior is
https://mobbr.com/#/crowds/brainstorm/media

which appears to follow this format
https://mobbr.com/#/crowds/:param1/:param2

What do param1 and param2 represent in this example?

**Comment by davidsemakula** [comment]
Check out https://github.com/mobbr/mobbr-frontend/pull/316 for a fix for this issue
