### ISSUE TITLE
Allow users to enter and invite email adressen on the crowds page

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#72]
Nice to have: an edit box to enter email-adresses, usernames and ID's to invite. The API already supports this.

**Comment by davidsemakula** [comment]
@patricksavalle 
The API endpoint /api_v1/persons/invite can receive an array of ids via POST
QN 1: Can the ids array contain a mixture of email addresses, usernames and ID's?
So that what the users enter in the edit box is what is sent to the endpoint.

If answer to QN 1 is NO? 
I see that /api_v1/persons/info can be used to exchange a username for a person object.
I'm assuming /api_v1/persons/uri can do the same for an URL (or ID) - I could be wrong on this one.
But I see no equivalent endpoint for exchanging an email for a person object.

**Comment by patricksavalle** [comment]
@davidsemakula Yes.

This methods accepts usernames and email-addresses.  But I would suggest just sending everything the user enters.

**Comment by davidsemakula** [comment]
Ok let me implement that then.

**Comment by davidsemakula** [comment]
Checkout https://github.com/mobbr/mobbr-frontend/pull/319 for a fix for this issue
